// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6boo9eQ4c0RWCLJ4EObJJHl4_CcIRjc',
    appId: '1:396448555814:web:35f22f98e00eb3573517e7',
    messagingSenderId: '396448555814',
    projectId: 'firebase-validator-app',
    authDomain: 'fir-validator-app.firebaseapp.com',
    storageBucket: 'firebase-validator-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNew-nHONsKrgZI0D2ikdtkiDjnSI3i3Q',
    appId: '1:396448555814:android:e088f1a21fe6e2593517e7',
    messagingSenderId: '396448555814',
    projectId: 'firebase-validator-app',
    storageBucket: 'firebase-validator-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPQW7n7jDAFnCoCSY7WYUfuuqFCwgR2yo',
    appId: '1:396448555814:ios:bf3c90888294c1bd3517e7',
    messagingSenderId: '396448555814',
    projectId: 'firebase-validator-app',
    storageBucket: 'firebase-validator-app.firebasestorage.app',
    iosBundleId: 'com.startup.validator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPQW7n7jDAFnCoCSY7WYUfuuqFCwgR2yo',
    appId: '1:396448555814:ios:bf3c90888294c1bd3517e7',
    messagingSenderId: '396448555814',
    projectId: 'firebase-validator-app',
    storageBucket: 'firebase-validator-app.firebasestorage.app',
    iosBundleId: 'com.startup.validator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm6boo9eQ4c0RWCLJ4EObJJHl4_CcIRjc',
    appId: '1:396448555814:web:36bd007cefa4b7473517e7',
    messagingSenderId: '396448555814',
    projectId: 'firebase-validator-app',
    authDomain: 'fir-validator-app.firebaseapp.com',
    storageBucket: 'firebase-validator-app.firebasestorage.app',
  );

}